-- Custom db migration: Not generated by prisma --

CREATE OR REPLACE FUNCTION delete_equipment_on_machineDescription_delete()
RETURNS TRIGGER AS $$
BEGIN
  DELETE FROM "EquipmentDescription" WHERE "id" = OLD."equipmentId";
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER delete_equipment_trigger
AFTER DELETE ON "MachineDescription"
FOR EACH ROW
EXECUTE FUNCTION delete_equipment_on_machineDescription_delete();