-- Custom db migration: Not generated by prisma --

ALTER TABLE "MachineDescription" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();

ALTER TABLE "MachineDescription" ALTER COLUMN "mainEquipmentId" SET DEFAULT gen_random_uuid();

ALTER TABLE "EquipmentDescription" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();

ALTER TABLE "StatusField" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();

ALTER TABLE "EventDescription" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();

ALTER TABLE "EventScopingRule" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();

ALTER TABLE "EventAbstractionRule" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();

ALTER TABLE "EventEnrichmentRule" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();

